name: Flutter Build

on:
  push:
    branches:
      - 'golden-version'
  workflow_dispatch: # هذا السطر هو الذي يُفعل زر التشغيل اليدوي!

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    # بناء النسخة النهائية السريعة والمحسنة
    - name: Build APK
      run: flutter build apk --release --split-per-abi

    # استخراج رقم الإصدار من pubspec.yaml
    - name: Extract version
      id: extract_version
      run: |
        VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //' | tr -d '\r')
        echo "VERSION=v$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      if: github.ref == 'refs/heads/golden-version' && github.event_name == 'push'

    - name: Check if Tag Exists
      id: check_tag
      run: |
        if git ls-remote --tags origin | grep -q "refs/tags/${{ env.VERSION }}"; then
          echo "TAG_EXISTS=true" >> $GITHUB_ENV
        else
          echo "TAG_EXISTS=false" >> $GITHUB_ENV
        fi

    # إنشاء Git Tag تلقائي
    - name: Create Git Tag
      if: github.ref == 'refs/heads/golden-version' && github.event_name == 'push' && env.TAG_EXISTS == 'false'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag ${{ env.VERSION }}
        git push origin ${{ env.VERSION }}
      continue-on-error: true # In case tag already exists

    # رفع وحفظ الملف لكي يظهر لك زر التحميل
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/*.apk

    # إنشاء GitHub Release أوتوماتيكياً
    - name: Create GitHub Release
      if: github.ref == 'refs/heads/golden-version' && github.event_name == 'push' && env.TAG_EXISTS == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        files: build/app/outputs/flutter-apk/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
